### ISSUE TITLE
where do i find the AZURE_RESOURCE?

### ISSUE THREAD

**Issue by lxg95** [rootinc/laravel-azure-middleware#10]
Hello,

I don't know what to use for the AZURE_RESOURCE-Parameter in my .env-file.
[This OAuth Guide](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code#request-an-authorization-code) tells me to look for an "App ID URI of the target web API" in the azure-portal, which i can find when i "click Azure Active Directory, click Application registrations, open the application's Settings page, then click Properties."
But i cannot find anything that is called "Properties" or "App ID URI" at my application's Settings page.
Do i have to use the "Microsoft Graph API endpoint" from the applications Endpoints?

Thank you very much in advance

Best regards
lxg95

**Comment by danieltjewett** [comment]
I remember this being tricky to figure out as well.  We're simply using `AZURE_RESOURCE=https://graph.windows.net`.

This might be a helpful read: https://stackoverflow.com/questions/23921884/what-is-the-resource-parameter-in-windows-azure-ad-tenant-application-oauth-2-0

**Comment by lxg95** [comment]
Nice that's helping a lot! Thank you :)
