### ISSUE TITLE
Ability to see users groups

### ISSUE THREAD

**Issue by JustinByrne** [rootinc/laravel-azure-middleware#11]
I can get the users name and email. Is there a way to also pull the users groups?

I have added the following API permissions:

**Microsoft Graph**
- Group.Read.All
- User.Read
- User.Read.All

But when I look at the `$profile` array it doesn't change.

**Comment by danieltjewett** [comment]
We have not had that use case yet.  Let me look into a bit and get back with you.

**Comment by danieltjewett** [comment]
I haven't found anything concrete yet, but it maybe with the current authentication flow, the `$profile` array is limited.  https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code

It maybe possible to extend this middleware to make a call out to more profile data.  That flow looks like it is here:
Id Tokens (parsing data from Azure): https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens
Optional Data from the Token: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims

My reading so far makes it seem that the `$profile` array would be populated when `response_type` 
 is `id_token`, but this makes the "authentication" part of this package no longer work.  To support this request, we may need another call to the Azure server that sends a request with the above `response_type`.

We currently have 0.7 in review, which will allow overriding the `azure` url.  In meantime we can override `azure` method manually below:

```
public function getAzureUrl()
{
    //notice response_type=code
    return $this->baseUrl . env('AZURE_TENANT_ID') . $this->route . "authorize?response_type=code&client_id=" . env('AZURE_CLIENT_ID') . "&resource=" . urlencode(env('AZURE_RESOURCE'));
}

public function azure(Request $request)
{
    return redirect()->away( $this->getAzureUrl() . "&moreparams=data" );
}
```

Here is the current azurecallback method, once a successful handshake with the azure server has happened.  This could be a base of figuring out how to make an additional call out to the Azure server for more profile data:

```
    public function azurecallback(Request $request)
    {
        $client = new Client();

        $code = $request->input('code');

        try {
            $response = $client->request('POST', $this->baseUrl . env('AZURE_TENANT_ID') . $this->route . "token", [
                'form_params' => [
                    'grant_type' => 'authorization_code',
                    'client_id' => env('AZURE_CLIENT_ID'),
                    'client_secret' => env('AZURE_CLIENT_SECRET'),
                    'code' => $code
                ]
            ]);

            $contents = json_decode($response->getBody()->getContents());
        } catch(RequestException $e) {
            return $this->fail($request, $e);
        }

        $access_token = $contents->access_token;
        $refresh_token = $contents->refresh_token;
        $profile = json_decode( base64_decode( explode(".", $contents->id_token)[1]) );

        $request->session()->put('_rootinc_azure_access_token', $access_token);
        $request->session()->put('_rootinc_azure_refresh_token', $refresh_token);

        return $this->success($request, $access_token, $refresh_token, $profile);
    }
```

I'll do some more digging at a later date.  If you find anything you'd like to contribute, feel free to submit a PR!

**Comment by JustinByrne** [comment]
I have found something that should work to resolve this, I'm currently testing my fork I will then create a PR once I'm happy it's working correctly.
