### ISSUE TITLE
Error with laravel 8

### ISSUE THREAD

**Issue by gnujach** [rootinc/laravel-azure-middleware#30]
Hi, i have problem with Laravel 8 it add the package  "guzzlehttp/guzzle": "^7.0.1" but laravel-azure-middleware require "guzzlehttp/guzzle": "^6.3" how can i resolve?
thank!!

**Comment by danieltjewett** [comment]
Hi @gnujach.  We bumped the version of guzzle to use anything above 6.2.  See if doing a `composer update` resolves this issue.

**Comment by gnujach** [comment]
Thank Dan!!

**Comment by danieltjewett** [comment]
Fixed in f872b075f65723cc1b5955901149b18eecae78f6
