### ISSUE TITLE
SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by TheGlitch1** [rootinc/laravel-azure-middleware#35]
Hello 

I receive this issue in the azureCallBack. I'm using laravel 7.
tried to update my certificat in php.ini but not resolved , also my GuzzleHttp version is ^6.3.

GuzzleHttp\Exception\RequestException
cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

I'm working in local dev env.
 can you please help me with this error.

**Comment by danieltjewett** [comment]
@TheGlitch1  We ran into something similar on another internal project using Guzzle.

On https://github.com/rootinc/laravel-azure-middleware/blob/master/src/Azure.php#L141, we make a call to Microsoft's servers.  Try copy / pasting the entire function into your extended class.  Then, after `'form_params'` array, add:  ` 'verify' => env("APP_ENV") === "production", //for local development`.  The block will look something like this:

```
$response = $client->request('POST', $this->baseUrl . config('azure.tenant_id') . $this->route . "token", [
    'form_params' => [
        'grant_type' => 'refresh_token',
        'client_id' => config('azure.client.id'),
        'client_secret' => config('azure.client.secret'),
        'refresh_token' => $refresh_token,
        'resource' => config('azure.resource'),
    ],
    'verify' => env("APP_ENV") === "production", //for local development
]);
```

This should fix the issue locally.  We always want to verify in production.  See https://docs.guzzlephp.org/en/stable/request-options.html#verify for more details.

If this works for you, perhaps submit a PR with the changes, as I am sure this could be useful for others using the package as well!

**Comment by TheGlitch1** [comment]
@danieltjewett thank you for your clear response I really appreciate it.
I tried your solution and it gave the same issue.

Apparently it's more related to the function success, with  
$graph_user = $graph->createRequest("GET", "/me")
                      ->setReturnType(Model\User::class)
                      ->execute();

I'm not sure if this a solution but I ended up removing $graph in the extended function success , and directly giving $profile properties to the updateOrCreate function. 

but I honestly feel that this is not the greatest thing to do.

**Comment by danieltjewett** [comment]
@TheGlitch1 `Graph` comes from Microsoft.  Perhaps they have options to allow for verifying SSL certificate on a request?  Another option, instead of using `Graph`, is to use the `$profile` from the original handshake from Azure.  We don't get as much detailed information, but we at least get `email`, `first_name` and `last_name`.

```
<?php

namespace App\Http\Middleware;

use RootInc\LaravelAzureMiddleware\Azure as Azure;

use Auth;

use App\User;

class AppAzure extends Azure
{
    protected function success($request, $access_token, $refresh_token, $profile)
    {
        $email = strtolower($profile->unique_name);

        $user = User::updateOrCreate(['email' => $email], [
            'firstName' => $profile->given_name,
            'lastName' => $profile->family_name
        ]);

        Auth::login($user, true);

        return parent::success($request, $access_token, $refresh_token, $profile);
    }
}
```

**Comment by TheGlitch1** [comment]
Thank you @danieltjewett for this useful package and all contributors !
