### ISSUE TITLE
Client error

### ISSUE THREAD

**Issue by francis-fullstack** [rootinc/laravel-azure-middleware#39]
Im getting this error, how to fix tihs?

Client error: `POST https://login.microsoftonline.com/(my id)/oauth2/token` resulted in a `401 Unauthorized` response: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: c346fff7-5 (truncated...)

**Comment by JustinByrne** [comment]
Sometimes you may need to clear your config cache, if your adding to a `.env` file of an existing project. Try running `php artisan config:clear` and see if it works after that.

**Comment by francis-fullstack** [comment]
I already use that sir, but error still appeared. I am clueless how to fix this.

here is the error screenshot: https://prnt.sc/10jh8pw
middleware: https://prnt.sc/10jhqfp

**Comment by francis-fullstack** [comment]
I use /v2.0/
then new error changed to:
https://prnt.sc/10jjhjj

**Comment by francis-fullstack** [comment]
I am using Laravel 8 . php 7.4
