### ISSUE TITLE
Session never expires

### ISSUE THREAD

**Issue by TheGlitch1** [rootinc/laravel-azure-middleware#41]
Hi everyone, 

I noticed that the session never expires when I log in with azure, but when I log in with a login and password my session expires after some time
Is there any way to logout the user after a while?

**Comment by JustinByrne** [comment]
In your `AppAzure.php` file you will have the following line

`Auth::login($user, true);`

Remove the `true` argument to prevent it from remembering the user

**Comment by JustinByrne** [comment]
Here is a link to the Laravel documentation with details about this method - https://laravel.com/docs/8.x/authentication#other-authentication-methods

**Comment by TheGlitch1** [comment]
Thank you JustinByrne !
