### ISSUE TITLE
Redirect to login page after logout

### ISSUE THREAD

**Issue by francis-fullstack** [rootinc/laravel-azure-middleware#42]
how to set Logout Redirect?

**Comment by danieltjewett** [comment]
@francis-fullstack this would need to be done in the Azure Portal.  Here is a screenshot of the input:

![image](https://user-images.githubusercontent.com/9869747/111478528-8a03f200-8706-11eb-9f27-fc15df343e7f.png)

**Comment by francis-fullstack** [comment]
I'm trying to redirect it to https://www.google.com to see if its working, but its not.

**Comment by danieltjewett** [comment]
@francis-fullstack Did you put `https://www.google.com` in the screenshot input above?

**Comment by francis-fullstack** [comment]
yes https://www.google.com, but its not working

and I have question, one application can only have  One Redirect URIs right?

**Comment by danieltjewett** [comment]
1. Are the routes setup correct?  For example:

```
//hit this directly in your browser, or add a logout button that points to `/logout/azure`.
Route::get('/logout/azure', '\App\Http\Middleware\AppAzure@azurelogout');

Route::get('/logout/azurecallback', function(Request $request) {
    //If you update the input from `https://www.google.com` to `https://yourwebsite.com/logout/azure`, you should see this route called.
});
```

2. I believe that is correct.

**Comment by francis-fullstack** [comment]
Thanks!!

lastly, I have two project, i run the ports 8888 and 8000. and I also created two app registration on portal so they can have separate redirect URI.
But  when I used 8888 im getting redirected at http://localhost:8000, they have same tenant ID

**Comment by francis-fullstack** [comment]
thank you!!

If im sucessfully logged in, how can I check in other controller if a user is logged in/authenticated?

and how can I protect my routes? thank you daniel.

**Comment by danieltjewett** [comment]
Make sure to have followed the steps here: https://github.com/rootinc/laravel-azure-middleware#extended-installation.  This package uses Laravel auth so anytime you want to check if a user is logged in / authenticated, you can use any of Laravel's auth methods:

https://laravel.com/docs/8.x/authentication#retrieving-the-authenticated-user
https://laravel.com/docs/8.x/authentication#determining-if-the-current-user-is-authenticated.

If you are in one of these controllers protected by the Azure middleware, you can *probably* assume the user is logged in at that point (I don't know what your code actually looks like, that is why I say *probably* 😉  )

Here is an example of protecting routes -- we just use the `group` function:

```
Route::get('/login/azurecallback', '\App\Http\Middleware\AppAzure@azurecallback');

Route::group([
  'middleware' => 'azure'
], function() {
    Route::get('/', 'IndexController@index');

    Route::get('/get-something', 'IndexController@getSomething`);

    ...
});
```

**Comment by francis-fullstack** [comment]
Got it thank you very much!!
