### ISSUE TITLE
Error in production: Declaration of App\Http\Middleware\AppAzure::success should be compatible with RootInc\LaravelAzureMiddleware\Azure::success

### ISSUE THREAD

**Issue by dagord** [rootinc/laravel-azure-middleware#44]
Hi all,
I've installed the package on Laravel 5.8 and wrote some simple routes just to test it out (actually, I my website consists only of a public route and a protected one!)
I registered my app on Azure environment, in order to get my TENANT_ID, APPLICATION_ID and so on.

I registered a new middleware in order to insert the user data to my database, accordingly to the documentation (https://github.com/rootinc/laravel-azure-middleware#extended-installation) 

So, on my developing environment (Ubuntu 18.04) I was able to implement it correctly: when I try to get to a protected route, I'm redirected to Microsoft login page and the user is returned correctly to my application. So far so good.

Then I decided to test the whole process on my production environment (MS Server 2016, with IIS 10.0.14393), but when trying to access the protected route, I get this error:
`Declaration of App\Http\Middleware\AppAzure::success($request, $access_token, $refresh_token, $profile) should be compatible with RootInc\LaravelAzureMiddleware\Azure::success(Illuminate\Http\Request $request, $access_token, $refresh_token, $profile)`

Both endpoints and redirection urls (for development and production environments) are correctly registered into my Azure app.
I tried to clear Laravel cache without luck.
I tried to delete the vendor directory and run **composer install** again... still no luck.

My route file:
`<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth as Auth;

Auth::routes();

Route::get('/login', '\App\Http\Middleware\AppAzure@azure');
Route::get('/login/azurecallback', '\App\Http\Middleware\AppAzure@azurecallback');

Route::get('/', function () {
    if (Auth::check())
        return redirect('/protected_area');
    $data = Array();
    $data['name'] = '';
    return view('test_page', $data);
});

Route::get('/protected_area', function () {
    $user = Auth::user();
    $data = Array();
    var_dump($user);
    $data['name'] = $user->name;
    return view('test_page', $data);
})->middleware('azure');`

**Comment by danieltjewett** [comment]
I think it might be as easy as adding `Illuminate\Http\Request $request` as the first parameter in `App\Http\Middleware\AppAzure::success(` instead of just `$request` (make sure to import the class).  We should update the README so that a copy / paste won't yield this problem.

**Comment by danieltjewett** [comment]
Just updated the `READme`.  Did the above help your problem?

**Comment by dagord** [comment]
Sorry for the late response.
I tested your suggestion today and it solved my problem (now I have another issue, but it seems related to IIS configuration).

Still, I can't understand why the middleware worked on my local environment but it "crashed" on production server.

**Comment by danieltjewett** [comment]
Perhaps there is a difference in configuration?  For example, maybe on the local environment, error catching is set much looser than on the production environment?  Glad the suggestion solved the problem.  I'm going to close the issue.
