### ISSUE TITLE
Refreshing token

### ISSUE THREAD

**Issue by francis-fullstack** [rootinc/laravel-azure-middleware#46]
Is there a existing method if my access token expired already, refresh token will be use to get a new access tokens? so the user will not sign in again just to get a new token

**Comment by danieltjewett** [comment]
There is not currently.  Feel free to submit a PR with the method!

**Comment by francis-fullstack** [comment]
Do you think this one would do? Screensht: https://prnt.sc/11dnxx1

**Comment by danieltjewett** [comment]
Code from the screenshot looks good.  It will be easier to tell in context with a pull request.
