### ISSUE TITLE
Error handling for AADSTS9002313

### ISSUE THREAD

**Issue by francis-fullstack** [rootinc/laravel-azure-middleware#47]
I already added the error code 

'AADSTS9002313' => [
                    'HTTP_CODE' => '400',
                    'msg' => 'You need to be B2B user in your tenant before you can login.',
 ],
 
 but it still cannot catch the error.

**Comment by francis-fullstack** [comment]
Client error: `POST https://login.microsoftonline.com/common/oauth2/token` resulted in a `400 Bad Request` response: {"error":"invalid_grant","error_description":"AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace (truncated...)

**Comment by francis-fullstack** [comment]
http://localhost:8888/api/login/azurecallback?code=M.R3_BAY.4efb63b3-8924-554c-c744-3f79512aa56c

**Comment by danieltjewett** [comment]
The current code https://github.com/rootinc/laravel-azure-middleware/blob/master/src/Azure.php#L190 is looking for a GET request.  The client error above says it is doing a POST.  Perhaps we have an error array for GETs and an error array for POSTs?  Unless the error strings can occur in both GETs and POSTs.  Then we could check if `isMethod('get') || isMethod('post')`

**Comment by jonatansantana** [comment]
I have a similar problem.
I cannot convert the json error response to an object.

Error responses are usually accompanied by the address requested on the first line, followed by a json with the error.

```
Client error: `POST https: // graph.microsoft.com / v1.0 / users` resulted in a` 403 Forbidden` response:
"{
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the ope (truncated ...)
"
```

Note that the json code is not complete.

In an attempt to capture the json to make it an object, I use the following piece of code to remove the first line that makes the json invalid:

`substr ($ exception-> getMessage (), strpos ($ exception-> getMessage (), "\ n") + 1);
`
And I have the following excerpt as a result:

```
"{
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the ope (truncated ...)
"

```
However, I still can't seem to make it an object. For it continues as a valid json.

Has anyone managed a solution for this?

I need to handle these error messages only.

**Comment by kaiqueprazeres** [comment]
> I have a similar problem.
> I cannot convert the json error response to an object.
> 
> Error responses are usually accompanied by the address requested on the first line, followed by a json with the error.
> 
> ```
> Client error: `POST https: // graph.microsoft.com / v1.0 / users` resulted in a` 403 Forbidden` response:
> "{
>   "error": {
>     "code": "Authorization_RequestDenied",
>     "message": "Insufficient privileges to complete the ope (truncated ...)
> "
> ```
> 
> Note that the json code is not complete.
> 
> In an attempt to capture the json to make it an object, I use the following piece of code to remove the first line that makes the json invalid:
> 
> `substr ($ exception-> getMessage (), strpos ($ exception-> getMessage (), "\ n") + 1); `
> And I have the following excerpt as a result:
> 
> ```
> "{
>   "error": {
>     "code": "Authorization_RequestDenied",
>     "message": "Insufficient privileges to complete the ope (truncated ...)
> "
> ```
> 
> However, I still can't seem to make it an object. For it continues as a valid json.
> 
> Has anyone managed a solution for this?
> 
> I need to handle these error messages only.

You can use the following code snippet to solve the problem:

`json_decode($exception->getResponse()->getBody()->read(1000));`

This will bring up the response in the form of a stdClass object.

Note: The value 1000 represents the size of the stream (response).
