### ISSUE TITLE
Error AADSTS500011

### ISSUE THREAD

**Issue by kallefrombosnia** [rootinc/laravel-azure-middleware#51]
Hello,
I am using this middleware for the project and Im facing some issues with Azure created app.
App is created and everything doing fine except callback from Azure where Azure returns this error:

```
{
  "error": "invalid_resource",
  "error_description": "AADSTS500011: The resource principal named {id} was not found in the tenant named {id} This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: \r\nCorrelation ID: \r\nTimestamp: 2021-06-01 09:55:53Z",
  "error_codes": [
    500011
  ],
  "timestamp": "2021-06-01 09:55:53Z",
  "trace_id": "",
  "correlation_id": "",
  "error_uri": "https://login.microsoftonline.com/error?code=500011"
}
```

I double-checked all info in the app and in the .env file. 
Really hard stuck here.

**Comment by danieltjewett** [comment]
This seems like a configuration issue the Azure App in the Azure Portal.  As the description state, either its posting to the wrong Tenant Id or the permissions are not set for the app.  I would look at your app registrations and verify the tenant id in the `env` matches as well as verify that permissions are set.

**Comment by kallefrombosnia** [comment]
After hours of debugging, I dropped this middleware and use PHP manual tutorial from their docs, and now it is working.
The app was made the same way as I tried before so something else was causing errors.
Sorry for bugging you.
