### ISSUE TITLE
How to make further Graph requests

### ISSUE THREAD

**Issue by martinkz** [rootinc/laravel-azure-middleware#57]
Hi, hopefully this question isn't completely out of place here.

Once authenticated using this middleware, what is the process of making further Graph/AD queries using the Graph REST API, elsewhere in the application, outside of the success/callback function? Is the access token still accessible somewhere?

**Comment by JustinByrne** [comment]
The token will need to be stored so it can be recalled when making further requests. I found this tutorial on how to do it. https://docs.microsoft.com/en-us/graph/tutorials/php
